version: "3.9"
services:
  prober:
    restart: unless-stopped
    build: .
    ports:
      - "8000:8000"
    environment:
     - PYTHONUNBUFFERED=1
    volumes:
      - type: bind
        source: ./probes.yml
        target: /etc/prober/probes.yml
        read_only: true
  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus/config/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - type: volume
        source: prometheus-storage
        target: /prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    depends_on:
      - prober
  grafana:
    restart: unless-stopped
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - type: bind
        source: ./grafana/config/grafana.ini
        target: /etc/grafana/grafana.ini
        read_only: true
      - type: bind
        source: ./grafana/provisioning/
        target: /etc/grafana/provisioning
      - type: bind
        source: ./grafana/dashboards/
        target: /etc/dashboards
        read_only: true
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana

volumes:
  grafana-storage:
  prometheus-storage:
