version: "3.9"
services:
  prober:
    container_name: prober
    restart: unless-stopped
    build: .
    ports:
      - "8000:8000"
    environment:
     - PYTHONUNBUFFERED=1
     - COLUMNS=200  # rich's log output defaults to super small 80 otherwise
    volumes:
      - type: bind
        source: ./probes.yml
        target: /etc/prober/probes.yml
        read_only: true
  vmagent:
    container_name: vmagent
    restart: unless-stopped
    image: victoriametrics/vmagent
    ports:
      - "8429:8429"
    volumes:
      - type: bind
        source: ./victoriametrics/config/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - type: volume
        source: vmagent-storage
        target: /vmagentdata
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    depends_on:
      - victoriametrics
  victoriametrics:
    container_name: victoriametrics
    restart: unless-stopped
    image: victoriametrics/victoria-metrics
    ports:
      - "8428:8428"
    volumes:
      - type: volume
        source: victoriametrics-storage
        target: /storage
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      - "--retentionPeriod=1"
  grafana:
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - victoriametrics
    volumes:
      - type: bind
        source: ./grafana/config/grafana.ini
        target: /etc/grafana/grafana.ini
        read_only: true
      - type: bind
        source: ./grafana/provisioning/
        target: /etc/grafana/provisioning
      - type: bind
        source: ./grafana/dashboards/
        target: /etc/dashboards
        read_only: true
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana

volumes:
  grafana-storage:
  victoriametrics-storage:
  vmagent-storage:
