version: "3.9"

services:

  prober:
    container_name: prober
    restart: unless-stopped
    build: .
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    environment:
     - PYTHONUNBUFFERED=1
     - COLUMNS=200  # rich's log output defaults to super small 80 otherwise
    volumes:
      - type: bind
        source: ./probes.yml
        target: /etc/prober/probes.yml
        read_only: true
    networks:
      - conn-probe-network

  vmagent:
    container_name: vmagent
    restart: unless-stopped
    image: victoriametrics/vmagent
    ports:
      - target: 8429
        published: 8429
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./victoriametrics/config/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - type: volume
        source: vmagent-storage
        target: /vmagentdata
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    depends_on:
      - victoriametrics
    networks:
      - conn-probe-network

  victoriametrics:
    container_name: victoriametrics
    restart: unless-stopped
    image: victoriametrics/victoria-metrics
    ports:
      - target: 8428
        published: 8428
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: victoriametrics-storage
        target: /storage
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      - "--retentionPeriod=1"
    networks:
      - conn-probe-network

  grafana:
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    depends_on:
      - victoriametrics
    volumes:
      - type: bind
        source: ./grafana/config/grafana.ini
        target: /etc/grafana/grafana.ini
        read_only: true
      - type: bind
        source: ./grafana/provisioning/
        target: /etc/grafana/provisioning
      - type: bind
        source: ./grafana/dashboards/
        target: /etc/dashboards
        read_only: true
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana
    networks:
      - conn-probe-network

volumes:
  grafana-storage:
    name: conn-probe-grafana-storage
  victoriametrics-storage:
    name: conn-probe-victoriametrics-storage
  vmagent-storage:
    name: conn-probe-vmagent-storage

networks:
  conn-probe-network:
    name: conn-probe-network
